spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#Data source properties
  datasource:
    driver-class-name: org.h2.Driver
    username: customer
    url: jdbc:h2:mem:customers
  h2:
    console:
      enabled: true
logging:
  level:
    web: DEBUG
